pipeline {
    // We use 'agent any' at the top level because we'll build our custom Docker image
    // in a specific stage and then use that image in subsequent stages.
    agent any

    environment {
        // --- Render Service URLs ---
        RENDER_DEV_URL = 'https://majd-kassem-business-dev.onrender.com/'
        RENDER_PROD_URL = 'https://majd-kassem-business.onrender.com/'

        // --- IMPORTANT: Render Live Service ID ---
        // Get this from your Render Dashboard URL for your Live service (e.g., srv-xxxxxxxxxxxxxxxxx)
        RENDER_LIVE_SERVICE_ID = 'srv-d0h686q4d50c73c6g410' // This is now correctly set

        // --- IMPORTANT: Jenkins Credential ID for Render API Key ---
        // This MUST match the ID you gave your Secret text credential in Jenkins.
        RENDER_API_KEY_CREDENTIAL_ID = 'render-api-key'

        // --- Consistent path for your JUnit XML report ---
        // This path is relative to the workspace INSIDE the Docker container.
        JUNIT_REPORT_FILE = 'test-results/junit-report.xml'

        // --- Consistent path for Allure raw data inside the Docker container's mounted workspace ---
        // NEW ENVIRONMENT VARIABLE FOR ALLURE RESULTS
        ALLURE_RESULTS_PATH_IN_CONTAINER = "/home/seluser/allure-results" 

        // --- Name for your custom Docker image ---
        CUSTOM_DOCKER_IMAGE_NAME = 'majd-selenium-runner'

        // --- Full Docker image name including tag, derived from BUILD_NUMBER ---
        FULL_DOCKER_IMAGE_NAME = "${CUSTOM_DOCKER_IMAGE_NAME}:${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Selenium Test Code') {
            steps {
                script {
                    // This checks out your Selenium test automation project from GitHub
                    git branch: 'dev', url: 'https://github.com/majd-j-kassem/majd.kassem.business_qa.git'
                    sh 'ls -la' // List files to verify checkout
                    echo "Selenium test code checked out."
                }
            }
        }

        stage('Build Custom Test Image') {
            steps {
                script {
                    echo "Building custom Docker image: ${env.FULL_DOCKER_IMAGE_NAME}"
                    // Build the Docker image. It will be automatically tagged with FULL_DOCKER_IMAGE_NAME
                    docker.build(env.FULL_DOCKER_IMAGE_NAME, ".")
                    echo "Custom Docker Image built: ${env.FULL_DOCKER_IMAGE_NAME}"
                }
            }
        }

        stage('Run Tests - Render Dev (CI Phase)') {
            agent {
                docker {
                    image env.FULL_DOCKER_IMAGE_NAME
                    // ADDED: Mount allure-results for Allure raw data
                    args """-v /dev/shm:/dev/shm -v ${WORKSPACE}/test-results:/home/seluser/test-results -v ${WORKSPACE}/allure-results:/home/seluser/allure-results"""
                }
            }
            steps {
                script {
                    echo "Running tests against Render Dev: ${env.RENDER_DEV_URL} inside custom Docker image."
                    // Create directory for JUnit report inside the container
                    sh "mkdir -p ${WORKSPACE}/test-results" // This directory is now inside the container, mapped to host.
                    // NEW: Create directory for Allure results on the host
                    sh "mkdir -p ${WORKSPACE}/allure-results" 

                    // Run pytest. Dependencies are now pre-installed in the image.
                    // MODIFIED: Added --alluredir to pytest command
                    sh "pytest src/tests --browser chrome-headless --base-url ${env.RENDER_DEV_URL} --junitxml=${env.JUNIT_REPORT_FILE} --alluredir=${env.ALLURE_RESULTS_PATH_IN_CONTAINER}"
                }
            }
            post {
                always {
                    // Publish JUnit test results for this stage in Jenkins UI
                    // The report file is mounted back to the host workspace, so Jenkins can find it.
                    junit "${WORKSPACE}/test-results/junit-report.xml"

                    // NEW: Generate and publish Allure Report
                    script {
                        try {
                            echo "Generating and publishing Allure Report..."
                            allure([
                                reportDir: 'allure-report', // Directory where the HTML report will be generated by Jenkins
                                results: ["allure-results"] // Directory where raw Allure XML/JSON data is located
                            ])
                            echo "Allure Report generated and published successfully."
                        } catch (Exception e) {
                            echo "Failed to generate Allure Report: ${e.message}"
                            // Optionally, mark the build as unstable or failed if Allure report generation is critical
                            // currentBuild.result = 'UNSTABLE'
                        }
                    }
                }
                failure {
                    echo "Tests against Render Dev FAILED! Build will stop here. ❌"
                }
                success {
                    echo "Tests against Render Dev PASSED! Proceeding to potential deployment. ✅"
                }
            }
        }

        stage('Deploy to Render Live (CD Phase)') {
            when {
                expression { currentBuild.result == null || currentBuild.result == 'SUCCESS' }
            }
            steps {
                script {
                    echo "Tests passed. Triggering deployment of the System Under Test to Render Live..."
                    withCredentials([string(credentialsId: env.RENDER_API_KEY_CREDENTIAL_ID, variable: 'RENDER_API_KEY')]) {
                        sh "curl -X POST -H \"Authorization: Bearer ${RENDER_API_KEY}\" \"https://api.render.com/v1/services/${env.RENDER_LIVE_SERVICE_ID}/deploys\""
                    }
                    echo "Deployment trigger sent to Render Live! Check Render dashboard for status."
                }
            }
            post {
                failure {
                    echo "Failed to trigger Render Live deployment! Please check API key, Service ID, or Render status. ❌"
                }
                success {
                    echo "Successfully triggered Render Live deployment. 🎉"
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    echo "Cleaning up workspace and removing custom Docker image..."
                    // Remove the generated report files from the host workspace
                    sh "rm -rf ${WORKSPACE}/test-results ${WORKSPACE}/allure-results ${WORKSPACE}/allure-report"
                    // Remove the custom Docker image to save space
                    sh "docker rmi -f ${env.FULL_DOCKER_IMAGE_NAME}"
                }
            }
        }
    }

    post {
        // Global actions after the entire pipeline finishes
        always {
            echo "Pipeline finished for job ${env.JOB_NAME}, build number ${env.BUILD_NUMBER}."
        }
        success {
            echo "Overall pipeline SUCCESS: All tests passed and Render Live deployment triggered. 🎉"
        }
        failure {
            echo "Overall pipeline FAILED: Some tests did not pass or deployment failed. ❌"
        }
        aborted {
            echo "Overall pipeline ABORTED: Build was manually stopped. 🚫"
        }
    }
}